baseURL = 'https://vishwa357.github.io/'
languageCode = 'en-us'
title = 'Vishwakant Mishra'
theme = 'PaperMod'

[params]
  author = 'Vishwakant Mishra'
  description = 'Software Engineer — Games, AR, HMI'
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  pluralizeListTitles = false

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Java'
    url = '/java/'
    weight = 2
